export const Type = {
	LASTFM_TRACK: 'LASTFM_TRACK',
	LASTFM_ALBUM: 'LASTFM_ALBUM',
	LASTFM_ARTIST: 'LASTFM_ARTIST',
	LASTFM_SIMILAR_ARTIST: 'LASTFM_SIMILAR_ARTIST',
	LASTFM_SIMILAR_TRACK: 'LASTFM_SIMILAR_TRACK',
	LASTFM_SEARCH: 'LASTFM_SEARCH',
	LASTFM_IMAGE: 'LASTFM_IMAGE',


	DEEZER_SEARCH: 'DEEZER_SEARCH',
	DEEZER_TRACK: 'DEEZER_TRACK',
	DEEZER_ALBUM: 'DEEZER_ALBUM',
	DEEZER_ARTIST: 'DEEZER_ARTIST',
	DEEZER_IMAGE: 'DEEZER_IMAGE',

	METRO_LYRICS: 'METRO_LYRICS',

	YOUTUBE_SEARCH: 'YOUTUBE_SEARCH',
	YOUTUBE_MATCH: 'YOUTUBE_MATCH',
	YOUTUBE_TRACK: 'YOUTUBE_TRACK',
	YOUTUBE_VIDEO: 'YOUTUBE_VIDEO',
	YOUTUBE_IMAGE: 'YOUTUBE_IMAGE',
	
	YOUTUBE_ORDER_TYPE: {
		DATE: 'date',
		RATING: 'rating',
		RELEVENCE: 'relevance',
		TITLE: 'title',
		VIDEO_COUNT: 'videoCount',
		VIEW_COUNT: 'viewCount'
	},
	
	YOUTUBE_PART_TYPE: {
		SNIPPET: 'snippet',
		CONTENT_DETAILS: 'contentDetails',
		STATISTICS: 'statistics'
	},

	MP3PM_MATCH: 'MP3PM_MATCH',
	MP3PM_TRACK: 'MP3PM_TRACK',
	MP3PM_RADIO: 'MP3PM_RADIO',

	MP3PM_RADIO_TYPE: {
		POP: 'pop',
		WORLD: 'world',
		DANCE: 'dance',
		ROCK: 'rock'
	},

	PLEER_MATCH: 'PLEER_MATCH',
	PLEER_TRACK: 'PLEER_TRACK',

	MIMP3_MATCH: 'MIMP3_MATCH',
	MIMP3_TRACK: 'MIMP3_TRACK',

	MP3COLD_MATCH: 'MP3COLD_MATCH',
	MP3COLD_TRACK: 'MP3COLD_TRACK',

	SOUNDCLOUD_MATCH: 'SOUNDCLOUD_MATCH',
	SOUNDCLOUD_TRACK: 'SOUNDCLOUD_TRACK',

	AISTEM_RADIO:'AISTEM_RADIO'
}